[app]
name = "demo"
host = "0.0.0.0"
port = "8050"
grpcport = "8051"
key  = "this is your app key"

[mysql]
host = "127.0.0.1"
port = "13306"
username = "root"
password = "root"
database = "cmdb"

[log]
level = "DEBUG"
path_dir = "logs"
format = "text"
to = "stdout"


